import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import {
  Box,
  Card,
  CardContent,
  CardHeader,
  Grid,
  Typography
} from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

type TPlantType = "Fruit" | "Vegetable";

interface IInitList {
  time?: number;
  name: string;
  type: TPlantType;
}

const initItems: IInitList[] = [
  {
    type: "Fruit",
    name: "Apple"
  },
  {
    type: "Vegetable",
    name: "Broccoli"
  },
  {
    type: "Vegetable",
    name: "Mushroom"
  },
  {
    type: "Fruit",
    name: "Banana"
  },
  {
    type: "Vegetable",
    name: "Tomato"
  },
  {
    type: "Fruit",
    name: "Orange"
  },
  {
    type: "Fruit",
    name: "Mango"
  },
  {
    type: "Fruit",
    name: "Pineapple"
  },
  {
    type: "Vegetable",
    name: "Cucumber"
  },
  {
    type: "Fruit",
    name: "Watermelon"
  },
  {
    type: "Vegetable",
    name: "Carrot"
  }
];

export default function Home() {
  const [initList, setInitList] = useState<IInitList[]>(initItems);
  const [plants, setPlants] = useState<IInitList[]>([]);

  const ColumnList = ({
    title,
    list
  }: {
    title: TPlantType;
    list: typeof initList;
  }) => {
    return (
      <Card
        sx={{ height: "100%", boxShadow: "none", border: "1px solid #eceff1" }}
      >
        <CardHeader
          title={title}
          sx={{ backgroundColor: "#eceff1", textAlign: "center" }}
        />
        <CardContent
          sx={{
            gap: "16px",
            display: "flex",
            flexDirection: "column",
            height: "100%"
          }}
        >
          {list.map((item, index: number) => {
            return (
              <Box
                padding={"12px"}
                border={"1px solid #eceff1"}
                key={index}
                sx={{ cursor: "pointer" }}
                onClick={() => onClickButton(item)}
              >
                <Typography variant={"h5"} textAlign={"center"}>
                  {item.name}
                </Typography>
              </Box>
            );
          })}
        </CardContent>
      </Card>
    );
  };

  const onClickButton = (item: IInitList) => {
    const find = plants.find((v) => v.name === item.name);
    const newItem = { ...item, time: new Date().getTime() };

    if (!find) {
      const newItems = [...plants, newItem] as IInitList[];

      setPlants(newItems);

      const movedList = initList.filter((list) => list.name !== item.name);
      setInitList(movedList);

      const timer = setTimeout(() => {
        onMoveBack(newItems, item);
      }, 5000);

      return () => clearTimeout(timer);
    } else {
      setPlants((prevState) => {
        return prevState.filter((_) => _.name !== item.name);
      });
      setInitList((prevState) => [...prevState, item]);
    }
  };

  const onMoveBack = (list: IInitList[], item: IInitList) => {
    list.forEach((obj) => {
      setPlants((prevState) => {
        return prevState.filter((prev) => prev.time !== obj.time);
      });
    });

    setInitList((prevState) => {
      const find = prevState.find((v) => v.name === item.name);
      return [...prevState, ...(!find ? [item] : [])];
    });
  };

  return (
    <>
      <Head>
        <title>TODO LIST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Grid container spacing={3} columns={{ xs: 4, sm: 8, md: 12 }}>
          <Grid container item xs={2} spacing={2} sm={4} md={4}>
            {initList.map((item, index: number) => {
              return (
                <Grid
                  item
                  xs={12}
                  key={index}
                  sx={{ cursor: "pointer" }}
                  onClick={() => onClickButton(item)}
                >
                  <Box
                    padding={"12px"}
                    border={"1px solid #eceff1"}
                    key={index}
                  >
                    <Typography variant={"h5"} textAlign={"center"}>
                      {item.name}
                    </Typography>
                  </Box>
                </Grid>
              );
            })}
          </Grid>
          {(["Fruit", "Vegetable"] as TPlantType[]).map(
            (item, index: number) => {
              return (
                <Grid item xs={2} sm={4} md={4} key={index}>
                  <ColumnList
                    title={item}
                    list={plants.filter((obj) => obj.type === item)}
                  />
                </Grid>
              );
            }
          )}
        </Grid>
      </main>
    </>
  );
}
